import json
from uuid import UUID
from llm.tools import LLMTools
from auth.tenant_context import get_tenant_id

class AgentOrchestrator:
    """
    Simulação do Agente LangChain.
    No MVP, substitui chamadas externas de LLM por lógicas de regex/match determinísticas
    para validar o ciclo de "Function Calling" isolando as APIs.
    (O Llama-3/Gemma real pode ser 'plugado' apenas trocando a engine interna).
    """

    SYSTEM_PROMPT = """Você é um assistente IA especialista em logística e gestão de estoque multi-tenant.
    Sua função é interpretar as intenções do usuário e retorná-las ESTRITAMENTE em formato JSON.
    Regras de Segurança: O tenant_id fornecido pelo orquestrador DEVE ser mantido isolado e em sigilo matemático nas transações (OWASP).
    Saída Estrita: RESPONDA APENAS com o JSON da transação correspondente (ex: {"action": "CadastrarProduto", "params": {...}}). ZERO texto explicativo fora do JSON.
    Explicabilidade: Em caso de falha nas regras de negócio da transação, adicione um campo "motivo" na sua resposta estruturada.
    """

    @staticmethod
    async def process_message(tenant_id: UUID, message: str) -> str:
        """
        Recebe a intenção no prompt de usuário, "interpreta" o tool call
        e retorna em JSON formatado.
        """
        from llm.parser import LLMOuputValidator
        from llm.governance import GovernanceRules
        
        msg_lower = message.lower()
        
        # Função auxiliar interna para garantir validação
        def parse_and_govern(raw_json_str: str) -> str:
            validated_intent = LLMOuputValidator.validate_and_parse(raw_json_str)
            governed_intent = GovernanceRules.evaluate_action(validated_intent)
            return json.dumps(governed_intent)

        
        # Simula extração de intenção: Movimentação (Entrada/Saída)
        if "entrad" in msg_lower or "receb" in msg_lower:
            q_str = [word for word in msg_lower.split() if word.isdigit()]
            qty = float(q_str[0]) if q_str else 1.0
            
            tool_resp = await LLMTools.record_movement(
                tenant_id=tenant_id, 
                product_code="TEST-001", 
                type="ENTRY", 
                quantity=qty
            )
            resp_dict = json.loads(tool_resp)
            if resp_dict["status"] == "success":
                return parse_and_govern(json.dumps({"action": "Entry", "params": {"product": "TEST-001", "quantity": qty}, "status": "success", "new_balance": resp_dict['new_balance']}))
            else:
                return parse_and_govern(json.dumps({"action": "Entry", "params": {"product": "TEST-001", "quantity": qty}, "status": "failed", "motivo": resp_dict['message']}))

        elif "saíd" in msg_lower or "said" in msg_lower or "vend" in msg_lower:
            q_str = [word for word in msg_lower.split() if word.isdigit()]
            qty = float(q_str[0]) if q_str else 1.0
            
            tool_resp = await LLMTools.record_movement(
                tenant_id=tenant_id, 
                product_code="TEST-001", 
                type="EXIT", 
                quantity=qty
            )
            resp_dict = json.loads(tool_resp)
            if resp_dict["status"] == "success":
                return parse_and_govern(json.dumps({"action": "Exit", "params": {"product": "TEST-001", "quantity": qty}, "status": "success", "new_balance": resp_dict['new_balance']}))
            else:
                return parse_and_govern(json.dumps({"action": "Exit", "params": {"product": "TEST-001", "quantity": qty}, "status": "failed", "motivo": resp_dict['message']}))
                
        # Simula extração de OCR de Recibos/Notas (Fase Financeira)
        elif "invoice" in msg_lower or "ocr" in msg_lower or "nota fiscal" in msg_lower or "fornecedor:" in msg_lower:
            # We simulate the LLM extracting JSON out of the OCR block exactly as generated by mock_receipt.png
            # If it's the domain receipt:
            if "tecidos finos" in msg_lower or "2.300" in msg_lower:
                return parse_and_govern(json.dumps({
                    "action": "RegisterExpense",
                    "params": {
                        "value": 2300.0,
                        "category": "Matéria Prima",
                        "date": "2026-03-12",
                        "supplier": "TECIDOS FINOS LTDA"
                    },
                    "status": "success"
                }))
            else:
                return parse_and_govern(json.dumps({
                    "action": "RegisterExpense",
                    "params": {
                        "value": 150.0,
                        "category": "Logística",
                        "date": "2026-03-12",
                        "supplier": "Transporte S/A"
                    },
                    "status": "success"
                }))
            
        # Simula extração de intenção: Administração ativa / plano executivo
        elif (
            "administrador" in msg_lower
            or "administra" in msg_lower
            or "prioridade" in msg_lower
            or "plano de ação" in msg_lower
            or "plano de acao" in msg_lower
        ):
            tool_resp = await LLMTools.get_admin_overview(tenant_id=tenant_id)
            resp_dict = json.loads(tool_resp)

            if resp_dict["status"] != "success":
                return parse_and_govern(json.dumps({
                    "action": "AdminPlan",
                    "status": "failed",
                    "motivo": resp_dict.get("message", "Falha ao montar o plano administrativo."),
                }))

            overview = resp_dict["data"]
            return parse_and_govern(json.dumps({
                "action": "AdminPlan",
                "status": "success",
                "data": overview,
                "motivo": (
                    f"Plano executivo gerado com {overview.get('low_stock_count', 0)} "
                    "item(ns) com estoque abaixo do mínimo."
                ),
            }))

        # Simula extração de intenção: Status do Estoque
        elif "estoque" in msg_lower or "resumo" in msg_lower:
            tool_resp = await LLMTools.get_inventory_status(tenant_id=tenant_id)
            resp_dict = json.loads(tool_resp)
            items = resp_dict.get("data", [])
            return parse_and_govern(json.dumps({"action": "InventoryStatus", "status": "success", "data": items}))
            
        else:
            return parse_and_govern(json.dumps({"action": "Unknown", "status": "failed", "motivo": "Comando não reconhecido pelo vocabulário de logística e estoque da plataforma."}))
